### ISSUE TITLE
Нестрогое равенство

### ISSUE THREAD

**Issue by pecourses** [Alex-it-work/JS-intro-hw#1]
https://github.com/Alex-it-work/JS-intro-hw/blob/39432d82d4a0e5a1d495156750456600046ae7c7/js/index.js#L66
- рекомендуем использовать всегда строгое (не)равенство, дабы избежать потенциальных ошибок. Сегодня разраб отследил, что всё корректно привел к одному типу, а завтра он (или кто будет поддерживать проект) реализовывает новую фичу и уже забывает отследить этот момент.

**Comment by Alex-it-work** [comment]
+
