### ISSUE TITLE
Расчетная формула

### ISSUE THREAD

**Issue by pecourses** [Alex-it-work/JS-intro-hw#2]
https://github.com/Alex-it-work/JS-intro-hw/blob/39432d82d4a0e5a1d495156750456600046ae7c7/js/index.js#L88
- насколько я помню, такой подход в большей степени применим при сложении, чтобы привести временно вещественные числа к целым, сложить (избежав ошибок при работе с вещественнцыми числами), и снова вернуть на круги своя, типа как (0.2\*10+0.1\*10)/10 вместо 0.2+0.1.
- копейки никто не отменял. Возможно, вы не в том месте поставили открывающую скобку.

**Comment by Alex-it-work** [comment]
убрал внешние скобки, они лишние. смысл в том что бы округлить остатки меньше одной копейки в пользу магазина в случаях если скидку зададут допустим  3,5%. При целых процентах скидки, по моему, такое окргление не требуется, поэтому можно просто было бы умножить price на 0,95 или 0,97.
