### ISSUE TITLE
Оптимизация

### ISSUE THREAD

**Issue by pecourses** [Alex-it-work/JS-intro-hw#3]
https://github.com/Alex-it-work/JS-intro-hw/blob/39432d82d4a0e5a1d495156750456600046ae7c7/js/index.js#L116
- всё корректно, только если бы там вычисления были более громоздкими, то эффективнее было бы сам счетчик инкрементировать на 5 (а так на каждой итерации еще плюс проверка условия). Исправлять не обязательно, это ремарка.

**Comment by Alex-it-work** [comment]
Я почему то посчитал что в задании нужно именно перебрать все числа (как если бы числа по порядку подчинялись какому то закону как на практике, а не шли банально +1) что бы из них отобрать кратные 5 используя %. А так конечно +5 лучшее решение.
