### ISSUE TITLE
именование функции

### ISSUE THREAD

**Issue by pecourses** [Alex-it-work/JS-intro-hw#4]
https://github.com/Alex-it-work/JS-intro-hw/blob/e59d834c50a1ac8892c469b5e2962f6526bae5ca/js/funcObj.js#L25
- придерусь к названию)  Имя функции должно как можно более точно передавать ее суть. Тут, по сути, основная цель ввести. Ну, на крайняк, ввести и проверить.

**Comment by Alex-it-work** [comment]
согласен) enterUserNumber вместо checkUserNumber
