### ISSUE TITLE
Параметризация

### ISSUE THREAD

**Issue by pecourses** [Alex-it-work/JS-intro-hw#5]
https://github.com/Alex-it-work/JS-intro-hw/blob/e59d834c50a1ac8892c469b5e2962f6526bae5ca/js/funcObj.js#L216
- как правило, если метод предназначен для изменения значения свойства, то в него параметром передают новое значение. Хотя, с точки зрения конкретной предметной области, наверное, логично менять пол не больше одного раза)

**Comment by Alex-it-work** [comment]
Эта предметная тема очень резонансная, раньше считалось что гендеров более 70 )) https://kub.media/news/1893-slozhna-pamagiti/
исправил
