### ISSUE TITLE
тип данных

### ISSUE THREAD

**Issue by pecourses** [Alex-it-work/JS-intro-hw#7]
https://github.com/Alex-it-work/JS-intro-hw/blob/e59d834c50a1ac8892c469b5e2962f6526bae5ca/js/funcObj.js#L241
- зачастую год логично делать числом для возможности вычислений, например, для определения возраста книги.

**Comment by Alex-it-work** [comment]
Конкретно для этой книги исправил.
Но у меня 2я книга   514-495 до н э   -  "r. 514–495 BC"  и я не завидую тому кому надо будет это считать)  оставил стринг.
